version: '2'
services:
    jhipstersampleapplication-app:
        image: jhipstersampleapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://admin:Iaqu9102Ya@68.183.129.197
            - SPRING_DATA_MONGODB_DATABASE=haraj
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jhipstersampleapplication-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    jhipstersampleapplication-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersampleapplication-mongodb
    jhipstersampleapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersampleapplication-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
